name: Deploy to server

on:
    push:
        branches:
            - main

jobs:
    # set-up:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: hola mundo
    #           run: echo "hola mundo 2"

    # deploy:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Hola mundo
    #           run: echo "${{ secrets.name }}"
    #     needs: set-up

    test-actions:
        runs-on: ubuntu-latest
        steps:
            - name: actions
              run: ls -al
