name: Deploy to server

on:
    - push

jobs:
    set-up:
        runs-on: ubuntu-latest
        steps:
            - name: hola mundo
              run: echo "hola mundo 2"

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Hola mundo
              run: echo "hola mundo"
        needs: set-up
